version: "3.4"

services:
    shipmonk-packing-mysql:
        image: mysql:8
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: packing
        hostname: mysql

    shipmonk-packing-app:
        build: .
        working_dir: /app
        user: ${UID:-1000}:${GID:-1000}
        volumes:
          - .:/app
